[project]
name = "llm_rename"
version = "0.1"
description = "An `llm` plugin to assist with renameutils qcp/qmv commands."
authors = [{name = "Yaniv Aknin", email = "yaniv@aknin.name"}]
license = {text = "MIT License"}
dependencies = ["llm"]

[project.entry-points.llm]
prochat = "llm_rename"

